name: QWC2 Build
on: [push]

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install all required dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get -y install jq

      - name: Check package version
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            VERSION=$(basename ${{ github.ref }})
            if [[ $VERSION == *-lts ]]; then
              VERSION=$(echo $VERSION | sed -E 's|v([0-9]+).([0-9]+)-lts|v\1.0.\2-lts|')
            fi
            # Abort if version is not the same as in package.json
            PKGVERSION=$(jq -r '.version' package.json)
            if [ "$VERSION" != "v$PKGVERSION" ]; then
              echo "Version mismatch: tag is ${VERSION}, package.json version is ${PKGVERSION}"
              exit 1
            fi
          fi

      - name: Compile a deployable application bundle
        run: npm run prod

      - name: Create zip
        run: zip -r qwc2-stock-app.zip prod/

      - name: Get tags
        id: get_tags
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            RELEASE_TAG=$(basename ${{ github.ref }})
          else
            CI_LATEST_TAG=ci-latest-$(basename ${{ github.ref }})
            # Delete previous release
            release_url=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${CI_LATEST_TAG}" | jq -r .url)
            if [ -n "$release_url" ] && [ "$release_url" != "null" ]; then
              curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X DELETE ${release_url}
            fi
            # Reset ci-latest tag
            git config --global user.email "ci@github.com"
            git config --global user.name "Github CI"
            # Workaround for "could not read Username for 'https://github.com': No such device or address"
            git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
            git tag -d $CI_LATEST_TAG || true
            git push origin :$CI_LATEST_TAG || true
            git tag -m $CI_LATEST_TAG $CI_LATEST_TAG
            git push --tags
          fi

          echo "ci_latest_tag=${CI_LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "release_tag=${RELEASE_TAG/null/}" >> $GITHUB_OUTPUT
        env:
          # This token is provided by Actions, you do not need to create your own token.
          # The token is only valid for one hour.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Create ci-latest release
        id: create_ci_latest_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_tags.outputs.ci_latest_tag }}
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./qwc2-stock-app.zip
        if: github.event_name != 'pull_request' && steps.get_tags.outputs.ci_latest_tag != ''

      - name: Create versioned release
        id: create_versioned_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_tags.outputs.release_tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./qwc2-stock-app.zip
        if: steps.get_tags.outputs.release_tag != ''

      - name: Publish to NPM
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          npm install -g npm@11
          npm run dist
          pushd dist
          npm publish
          popd
